### ISSUE TITLE
score gap in gsm8k between llama2-7b 16bit and int2g128 model

### ISSUE THREAD

**Issue by dengzheng-cloud** [DD-DuDa/BitDistiller#11]
i have followed readme.md to qat-train a int2g128 llama2 7b model. and its wiki test score match paper submitted.
after that i tested the checkpoint model **without pseudo quantization** with llama2 7b and llama2 7b-awq in gsm8k, by lm_eval 0.4.4, models run with vllm0.6.4post1.
llama 2 7b got 
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value|   |Stderr|
|-----|------:|----------------|-----:|-----------|---|----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.244|±  |0.0272|
|     |       |strict-match    |     5|exact_match|↑  |0.228|±  |0.0266|

llama2 7b-awq got 
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value|   |Stderr|
|-----|------:|----------------|-----:|-----------|---|----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.204|±  |0.0255|
|     |       |strict-match    |     5|exact_match|↑  |0.160|±  |0.0232|

llama2 7b int2g128 without pseudo quantize
|Tasks|Version|     Filter     |n-shot|  Metric   |   |Value|   |Stderr|
|-----|------:|----------------|-----:|-----------|---|----:|---|-----:|
|gsm8k|      3|flexible-extract|     5|exact_match|↑  |0.124|±  |0.0209|
|     |       |strict-match    |     5|exact_match|↑  |0.124|±  |0.0209|

would like to ask two questions:
1. are these results correct? or checkpoint cannot be used directly for model eval
2. how to run bitdistiller trained model with vllm(or other like trtllm)? maybe 4bit is also acceptable.

thanks.

**Comment by DD-DuDa** [comment]
The results seem reasonable. The original model was trained using QAT, which might significantly alter the weights, especially when using 2-bit quantization. If you perform inference without pseudo quantization, the model may not function as intended.

To run the model, refer to the [inference directory](https://github.com/DD-DuDa/BitDistiller/tree/main/inference). You need to replace the original linear layer with Qlinear. Ensure that Qlinear can perform inference using a low-bit kernel.

**Comment by dengzheng-cloud** [comment]
@DD-DuDa thank u, i'll try it.
