### ISSUE TITLE
4-bit or higher?

### ISSUE THREAD

**Issue by Saoyu99** [DD-DuDa/BitDistiller#2]
Have you conducted evaluations on the effects of quantization of 4 bits or higher?

**Comment by DD-DuDa** [comment]
Yes, our method is generally effective.

**Comment by brisker** [comment]
@DD-DuDa 
For the main results of the paper, have you ever done any experiments for w4_gs128?

**Comment by DD-DuDa** [comment]
Yeah.

**Comment by brisker** [comment]
@DD-DuDa 
Any performance details can be shared which are not in ther paper?
