### ISSUE TITLE
Question about 2-bit kerrel.

### ISSUE THREAD

**Issue by ChenMnZ** [DD-DuDa/BitDistiller#3]
Hello,

Thanks for your outstanding works. I am curious about the 2bit inference speedup.

I want to know which quantization kernel are used during the speed testing.

Is the kernel directly from GPTQ triton kernel, or have you made some improvements？

**Comment by DD-DuDa** [comment]
Thank you. Currently, we are utilizing AWQ Triton kernel for GEMM and AWQ CUDA kernel for GEMV. However, the original kernel we use does not support 2-bit, whereas we support 4/2 bit here. To further enhance our performance, we are considering integrating [BitBLAS](https://github.com/microsoft/BitBLAS/tree/main) in the future.

**Comment by ChenMnZ** [comment]
Good job. Thanks for your answer.
