### ISSUE TITLE
Question about the dataset size

### ISSUE THREAD

**Issue by helloworld77** [DD-DuDa/BitDistiller#5]
Hello, thanks for your great work.
I have some question about the dataset used in table6 of BitDistiller:
<img width="405" alt="image" src="https://github.com/DD-DuDa/BitDistiller/assets/16054417/b7a8bdd9-9c77-4462-9860-de70472e3b80">
LLM-QAT is datafree method, and from A.3 I get to know that BitDistiller only use "a small portion of the involved
datasets", so what is 100k and 2k data mean in table6?

**Comment by DD-DuDa** [comment]
100K and 2K represent the amount of data. LLM-QAT generates 100K data for training, while BitDistiller only requires 2K for training.
